name = input("Hello. What is your name? ")
age = input("It's nice to meet you, " + name + ". How old are you? ")
print("I see that you are still quite young at only " + age + ".")
home = input("Where do you live? ")
print("Wow! I've always wanted to go to " + home + ". Thanks for chatting with me. Bye!")